### PR TITLE
Port configurability

### LINKED ISSUE #4: Make port configurable.

### LINKED ISSUE #5: Error: logic not found
After finding the response, that data is passed to the logic function in the stub, but logic isn't mandatory, handle the case where the error is thrown when the logic function isn't found.

### PR DESCRIPTION
**Pull request by akhilgangula**
resolve 
#5 Handling Error logic
#4 Make port configurable

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -67,6 +67,6 @@ module.exports = (logicDir, dataDir, opts) => {
     });
 
 
-    const port = 3000;
-    app.listen(port, () => console.log(`Server started`));
+    const port = opts.port ? opts.port : 3000;
```
Comment (mattaharish) [inline index.js:70]: If I don't pass the port and If I'm running some other service on port 3000? We will get PORT already in use error.

**Review by mattaharish — APPROVED** [review]
